# Site settings
title: Armel's Webpages
email: armell.dev@outlook.com
description: "Some written stuff about the things I do with computers."
baseurl: ""
url: "http://armell.github.io"
#twitter_username: jekyllrb
github_username:  armell

# Build settings
markdown: kramdown
permalink: pretty
